export const SITE = {
  url: "https://renofixplus.ae",
  name: "RenoFix",
  phone: "+971 54 446 0966",
  whatsapp: "971544460966",
  email: "renofixplus@gmail.com",
  instagram: "renofixplus",
  licence: "1585059",
  city: "Dubai",
  // Default social share image, generated by app/opengraph-image.jsx.
  ogImage: "/opengraph-image",
  // Google Ads conversion tracking. leadLabel filled after creating a conversion action.
  gads: { id: "AW-18358000613", leadLabel: "" },
  // Google review link (from GBP -> "Ask for reviews"). Paste it here to enable the "Leave a review" buttons.
  googleReviewUrl: "",
};
